USE HRM
GO

/****** Object:  Table [dbo].[ADM_DEF_MONTH]    Script Date: 02/01/2020 21:19:50 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[HRM_DEF_MONTH](
	[CODE] [numeric](10, 0) NOT NULL DEFAULT ((0)),
	[DESC] [varchar](max) NULL DEFAULT (''),
	[MONT] [numeric](5, 0) NULL DEFAULT ((0)),
	[INACTIVE] [numeric](1, 0) NULL DEFAULT ((0)),
 CONSTRAINT [PK_ADM_DEF_MONTH] PRIMARY KEY CLUSTERED 
(
	[CODE] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


