USE HRM
GO

/****** Object:  Table [dbo].[HRM_MASTER_EXP]    Script Date: 31/12/2019 20:40:09 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[HRM_MASTER_EXP](
	[USER_CODE] [numeric](18, 0) NOT NULL,
	[CODE] [numeric](10, 0) NOT NULL,
	[COMPANY] [varchar](max) NULL DEFAULT (''),
	[TITLE] [varchar](max) NULL DEFAULT (''),
	[PHONE] [varchar](MAX) NULL DEFAULT (''),
	[EMAIL] [varchar](MAX) NULL DEFAULT (''),
	[FROM] [date] NULL,
	[TO] [date] NULL,
 CONSTRAINT [PK_HRM_MASTER_EXP] PRIMARY KEY CLUSTERED 
(
	[USER_CODE] ASC,
	[CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


