USE HRM
GO

/****** Object:  Table [dbo].[HRM_MASTER]    Script Date: 31/12/2019 20:37:47 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[HRM_MASTER](
	[CREATION] [date] NULL,
	[USER_CODE] int NOT NULL identity(1,1),
	[NAME] [varchar](max) NULL,
	[ADDRESS] [varchar](max) NULL,
	[DOB] [date] NULL,
	[CNIC] [numeric](16, 0) NULL,
	[FATHER] [varchar](max) NULL,
	[MOTHER] [varchar](max) NULL,
	[SPOUSE] [varchar](max) NULL CONSTRAINT [DF_HRM_MASTER_SPOUSE]  DEFAULT (''),
	[PHONE] [varchar](80) NULL,
	[CELL] [varchar](60) NULL,
	[EMAIL] [varchar](60) NULL,
	[GENDER] [numeric](10, 0) NULL,
	[MARITAL] [numeric](10, 0) NULL,
	[KIDS] [numeric](5, 0) NULL CONSTRAINT [DF_HRM_MASTER_KIDS]  DEFAULT ((0)),
	[PHOTO] [image] NULL,
	[EMP_CODE] [varchar](10) NULL DEFAULT (''),
	[EMP_STATUS] [numeric](10, 0) NULL DEFAULT ((0)),
	[LM_EMP_CODE] [varchar](10) NULL DEFAULT (''),
	[BRANCH_CODE] [numeric](10, 0) NULL DEFAULT ((0)),
	[DEPT_CODE] int NULL DEFAULT ((0)),
	[TITLE_CODE] int NULL DEFAULT ((0)),
	[SHIFT_CODE] int NULL CONSTRAINT [DF_HRM_MASTER_SHIFT_CODE]  DEFAULT ((0)),
	[DOJ] [date] NULL,
	[DOC] [date] NULL,
	[RESIGN] [numeric](1, 0) NULL CONSTRAINT [DF_HRM_MASTER_RESIGN]  DEFAULT ((0)),
	[RESIGN_DATE] [date] NULL,
	[BANK_AC_NO] [varchar](20) NULL CONSTRAINT [DF_HRM_MASTER_BANK_AC_NO]  DEFAULT (''),
	[AUTH_STATUS] [varchar](1) NULL CONSTRAINT [DF_HRM_MASTER_AUTH_STATUS]  DEFAULT ('P'),
	[AUTH_DATE] [datetime] NULL,
	[AUTH_BY] [numeric](10, 0) NULL CONSTRAINT [DF_HRM_MASTER_AUTH_BY]  DEFAULT ((0)),
	[AUTH_REMARKS] [varchar](max) NULL CONSTRAINT [DF_HRM_MASTER_AUTH_REMARKS]  DEFAULT (''),
	[INACTIVE] [numeric](1, 0) NULL CONSTRAINT [DF_HRM_MASTER_INACTIVE]  DEFAULT ((0)),
 CONSTRAINT [PK_HRM_MASTER] PRIMARY KEY CLUSTERED 
(
	[USER_CODE] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


