USE HRM
GO

/****** Object:  Table [dbo].[HRM_DEF_SHIFT]    Script Date: 31/12/2019 20:48:11 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[HRM_DEF_SHIFT_DAYS](
	SHIFT_HR NUMERIC(18,0) NOT NULL,
	[CODE] [numeric](18, 0) NOT NULL,
	[DESC] [varchar](max) NULL DEFAULT (''),
	DAY1_IN TIME(7),
	DAY1_OUT TIME(7),
	DAY2_IN TIME(7),
	DAY2_OUT TIME(7),
	DAY3_IN TIME(7),
	DAY3_OUT TIME(7),
	DAY4_IN TIME(7),
	DAY4_OUT TIME(7),
	DAY5_IN TIME(7),
	DAY5_OUT TIME(7),
	DAY6_IN TIME(7),
	DAY6_OUT TIME(7),
	DAY7_IN TIME(7),
	DAY7_OUT TIME(7),
	DAY8_IN TIME(7),
	DAY8_OUT TIME(7),
	DAY9_IN TIME(7),
	DAY9_OUT TIME(7),
	DAY10_IN TIME(7),
	DAY10_OUT TIME(7),
	DAY11_IN TIME(7),
	DAY11_OUT TIME(7),
	DAY12_IN TIME(7),
	DAY12_OUT TIME(7),
	DAY13_IN TIME(7),
	DAY13_OUT TIME(7),
	DAY14_IN TIME(7),
	DAY14_OUT TIME(7),
	DAY15_IN TIME(7),
	DAY15_OUT TIME(7),
	DAY16_IN TIME(7),
	DAY16_OUT TIME(7),
	DAY17_IN TIME(7),
	DAY17_OUT TIME(7),
	DAY18_IN TIME(7),
	DAY18_OUT TIME(7),
	DAY19_IN TIME(7),
	DAY19_OUT TIME(7),
	DAY20_IN TIME(7),
	DAY20_OUT TIME(7),
	DAY21_IN TIME(7),
	DAY21_OUT TIME(7),
	DAY22_IN TIME(7),
	DAY22_OUT TIME(7),
	DAY23_IN TIME(7),
	DAY23_OUT TIME(7),
	DAY24_IN TIME(7),
	DAY24_OUT TIME(7),
	DAY25_IN TIME(7),
	DAY25_OUT TIME(7),
	DAY26_IN TIME(7),
	DAY26_OUT TIME(7),
	DAY27_IN TIME(7),
	DAY27_OUT TIME(7),
	DAY28_IN TIME(7),
	DAY28_OUT TIME(7),
	DAY29_IN TIME(7),
	DAY29_OUT TIME(7),
	DAY30_IN TIME(7),
	DAY30_OUT TIME(7),
	DAY31_IN TIME(7),
	DAY31_OUT TIME(7),
	[AUTH_STATUS] [varchar](1) NULL DEFAULT ('P'),
	[AUTH_DATE] [datetime] NULL,
	[AUTH_BY] [numeric](18, 0) NULL DEFAULT ((0)),
	[AUTH_REMARKS] [varchar](max) NULL DEFAULT (''),
	[INACTIVE_HRM] [numeric](1, 0) NULL DEFAULT ((0)),
 CONSTRAINT [PK_HRM_DEF_SHIFT] PRIMARY KEY CLUSTERED 
(
	[CODE] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


