//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HRMEntities : DbContext
    {
        public HRMEntities()
            : base("name=HRMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<HRM_ATTEND> HRM_ATTEND { get; set; }
        public DbSet<HRM_DEF_ATEND_TYPE> HRM_DEF_ATEND_TYPE { get; set; }
        public DbSet<HRM_DEF_DESIG> HRM_DEF_DESIG { get; set; }
        public DbSet<HRM_DEF_EMP_TYPE> HRM_DEF_EMP_TYPE { get; set; }
        public DbSet<HRM_DEF_SHIFT_HRS> HRM_DEF_SHIFT_HRS { get; set; }
        public DbSet<HRM_DEF_SHIFT_TYPE> HRM_DEF_SHIFT_TYPE { get; set; }
        public DbSet<HRM_MASTER> HRM_MASTER { get; set; }
        public DbSet<HRM_MASTER_EDU> HRM_MASTER_EDU { get; set; }
        public DbSet<HRM_MASTER_EXP> HRM_MASTER_EXP { get; set; }
        public DbSet<HRM_MASTER_REF> HRM_MASTER_REF { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<HRM_DEF_SHIFT_DAYS> HRM_DEF_SHIFT_DAYS { get; set; }
    }
}
