//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRM_MASTER_EXP
    {
        public decimal USER_CODE { get; set; }
        public decimal CODE { get; set; }
        public string COMPANY { get; set; }
        public string TITLE { get; set; }
        public string PHONE { get; set; }
        public string EMAIL { get; set; }
        public Nullable<System.DateTime> FROM { get; set; }
        public Nullable<System.DateTime> TO { get; set; }
    }
}
