//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRM_MASTER_EDU
    {
        public decimal USER_CODE { get; set; }
        public decimal CODE { get; set; }
        public Nullable<decimal> EDU_CODE { get; set; }
        public Nullable<decimal> UNI_CODE { get; set; }
        public string GRADE { get; set; }
        public string PASS_YEAR { get; set; }
    }
}
