//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRM_MASTER_REF
    {
        public decimal USER_CODE { get; set; }
        public decimal CODE { get; set; }
        public string NAME { get; set; }
        public string PROF { get; set; }
        public string COMPANY { get; set; }
        public Nullable<decimal> REL { get; set; }
        public Nullable<decimal> REL_NOY { get; set; }
        public string PHONE { get; set; }
        public string CELL { get; set; }
        public string EMAIL { get; set; }
    }
}
